### ISSUE TITLE
pass SMTPSession to callback

### ISSUE THREAD

**Issue by holgerlembke** [mobizt/ESP-Mail-Client#22]
Hi K.,

I enjoy your ESP_Mail_Client.h.

I wrote a function to handle all my mail-send-needs and though I could have all needed vars local. Sadly that does not work if the callback is used like in "send-text" example.
```
  smtp.callback(smtpCallback);
``` 
As far as I see, why not add the reference to SMTPSession into the class SMTP_Status? Or change the callback-call to pass it (that would break compatibility, but lib is quite new...)?

Anyway, I would really prefer to avoid to create a global var (even if it might be only a pointer).

**Comment by mobizt** [comment]
You should use discussion instead of open the issue.

This is the design for reusable  TCP session in the SMTPSession and IMAPSession objects. 

The objects should be defined global to  prevent heap fragmentation for the large memory used by the SSL library.

The callback is design for long running task of sending or reading emails then the info can be accessed from the session object instead of copy or duplicate the internal class data to the SMTP_Status and IMAP_Status. 

For just send single message and you use SMTPSession as local object, the sending result is not important as the sendMail function returns true/false as the result of sending and you already know the info of a sent message.
