### ISSUE TITLE
Should NTP resync time be set to only 5 seconds here?

### ISSUE THREAD

**Issue by Plashu** [mobizt/ESP-Mail-Client#229]
I noticed NTP re-syncing on every email send even ones sent just 10 seconds apart, have changed it to 30min in my project.

https://github.com/mobizt/ESP-Mail-Client/blob/081ab139d4316b9d520cdf6920e2528d0160f87b/src/extras/MB_Time.h#L147

**Comment by mobizt** [comment]
The time was checked before sending request.

There is no further sending NTP server request if the valid time response once received and internal library time and/or device time was/were set.

The NTP request interval i.e., 10 seconds is for allowing UDP client to process the response which may delay due to internet condition.

If time is already set, the NTP time re-synch is only taken place when the GMT offset or time zone has  changed by user.

Then you do not need to change this request interval value.

**Comment by mobizt** [comment]
As I post above, time synching occurred only when time (library internal and/or device time) was not set, or time zone changed.

The time re-synching is not executed too often than 5 seconds in case of the time synching failure due to network issue and 5 seconds re-synching interval is long enough and suitable for the retry period. 

Library does not re-sync time before sending email but check the time first before synching.

The internal library time was used as reference to allow some devices that do not have time function to work.

Only ESP32, ESP8266 and Raspberry Pi Pico have the time function.
