### ISSUE TITLE
smtp.setTCPTimeout(10) not honored?

### ISSUE THREAD

**Issue by DigiHzData** [mobizt/ESP-Mail-Client#317]
**Build tool used:**

- [x ] Arudino
- [ ] Platformio (Visual Studio Code plugin)
- [ ] Platformio CLI
- [ ] Other

**Board used (ESP32/ESP8266/Arudino):**

- [ ] ESP8266-based
- [ x] ESP32-based

**Other Libraries That are used:**

**Description of problem:**

**Share code snippet to reproduce the issue:**
```yaml
PASTE .cpp / .ino code here

```

**Additional information and things you've tried:**

Sawadee kup.
Sa bai dee mai.

I am confused about if setTCPTimeout is working/honored or not.
I tried to not set setTCPTimeout and it seams to take about 20 seconds to timeout with a wrong set port.
if i set setTCPTimeout to 10, it still take about 20 seconds before canceling the connection.

I thought the setTCPTimeout value is the value for connecting to a server, but maybe i am wrong.
In any case, i wish there was a functionality to set a timeout for the connection we are trying to establish.
As it is now....if for example the port is set wrong, the library blocks for about 20 seconds.

Is there any way around this problem?

Thank you in advance.

**Comment by mobizt** [comment]
The timeout checking interval for each client data reading may be longer due to the internal SSL engine blocking operation. 

We do not force the client to stop to exit the SSL engine waiting loop immediately when timeout reached but wait until the SSL engine finished its job.

Then please don't set this timeout value too small otherwise you should use the external client and set the timeout of the external client instead.
